begin;
do $$
declare
  v_login text := 'test_last_'||substr(replace(gen_random_uuid()::text,'-',''),1,12);
  v_password text := encode(extensions.gen_random_bytes(24),'hex');
  v_user uuid; v_other uuid; v_admin uuid;
  v_token text; v_other_token text; v_admin_token text;
  v_driver bigint; v_v1 bigint; v_v2 bigint; v_contract bigint;
  v_old uuid := gen_random_uuid(); v_new uuid := gen_random_uuid();
  v_backdated uuid := gen_random_uuid(); v_foreign uuid := gen_random_uuid();
  v_today date := (now() at time zone 'America/Sao_Paulo')::date;
  v_result jsonb;
begin
  v_user := public.cadastrar_usuario(v_login,v_password,'funcionario','Teste','Histórico');
  v_other := public.cadastrar_usuario(v_login||'_o',v_password,'funcionario','Outro','Teste');
  v_admin := public.cadastrar_usuario(v_login||'_a',v_password,'admin','Admin','Teste');
  v_token := public.autenticar_usuario(v_login,v_password)->>'token';
  v_other_token := public.autenticar_usuario(v_login||'_o',v_password)->>'token';
  v_admin_token := public.autenticar_usuario(v_login||'_a',v_password)->>'token';
  insert into public.funcionarios(nome) values(v_login) returning id into v_driver;
  select id into strict v_v1 from public.veiculos where ativo order by id limit 1;
  select id into strict v_v2 from public.veiculos where ativo and id<>v_v1 order by id limit 1;
  select id into strict v_contract from public.contratos where ativo order by id limit 1;
  set local role anon;
  begin
    perform public.ultimo_veiculo_motorista(null,v_driver);
    raise exception 'Consulta sem sessao aceita' using errcode='XX000';
  exception when invalid_authorization_specification then null; end;
  if public.ultimo_veiculo_motorista(v_token,v_driver) is not null then raise exception 'Historico vazio incorreto'; end if;
  perform public.salvar_registro(v_token,v_old,v_today-3,v_contract,jsonb_build_array(jsonb_build_object('responsavel_id',v_driver,'veiculo_id',v_v1)));
  perform public.salvar_registro(v_token,v_new,v_today-1,v_contract,jsonb_build_array(jsonb_build_object('responsavel_id',v_driver,'veiculo_id',v_v2)));
  perform public.salvar_registro(v_token,v_backdated,v_today-2,v_contract,jsonb_build_array(jsonb_build_object('responsavel_id',v_driver,'veiculo_id',v_v1)));
  v_result := public.ultimo_veiculo_motorista(v_token,v_driver);
  if v_result is distinct from jsonb_build_object('vehicleId',v_v2,'date',v_today-1) then raise exception 'Data da alocacao nao priorizada'; end if;
  if public.ultimo_veiculo_motorista(v_token,v_driver,v_new) is distinct from jsonb_build_object('vehicleId',v_v1,'date',v_today-2) then raise exception 'Edicao nao excluiu registro atual'; end if;
  if public.ultimo_veiculo_motorista(v_other_token,v_driver) is not null then raise exception 'Funcionario leu historico alheio'; end if;
  perform public.salvar_registro(v_other_token,v_foreign,v_today,v_contract,jsonb_build_array(jsonb_build_object('responsavel_id',v_driver,'veiculo_id',v_v1)));
  if public.ultimo_veiculo_motorista(v_token,v_driver) is distinct from v_result then raise exception 'Historico alheio vazou'; end if;
  if public.ultimo_veiculo_motorista(v_admin_token,v_driver) is distinct from jsonb_build_object('vehicleId',v_v1,'date',v_today) then raise exception 'Admin nao leu ultima alocacao'; end if;
  perform public.editar_registro(v_token,v_new,v_today-1,v_contract,jsonb_build_array(jsonb_build_object('responsavel_id',v_driver,'veiculo_id',v_v1)),1);
  if (public.ultimo_veiculo_motorista(v_token,v_driver)->>'vehicleId')::bigint<>v_v1 then raise exception 'Correcao ignorada'; end if;
  perform public.editar_registro(v_token,v_new,v_today-1,v_contract,jsonb_build_array(jsonb_build_object('responsavel_id',v_driver,'veiculo_id',v_v2)),2);
  reset role;
  update public.veiculos set ativo=false where id=v_v2;
  set local role anon;
  if public.ultimo_veiculo_motorista(v_token,v_driver) is not null then raise exception 'Ultimo veiculo inativo sugerido ou substituido por historico antigo'; end if;
  reset role;
  update public.veiculos set ativo=true where id=v_v2;
  set local role anon;
  perform public.apagar_envio(v_admin_token,v_new,'registro');
  if public.ultimo_veiculo_motorista(v_token,v_driver) is distinct from jsonb_build_object('vehicleId',v_v1,'date',v_today-2) then raise exception 'Registro apagado continuou sugerido'; end if;
  reset role;
  update public.funcionarios set ativo=false where id=v_driver;
  set local role anon;
  if public.ultimo_veiculo_motorista(v_admin_token,v_driver) is not null then raise exception 'Motorista inativo sugerido'; end if;
  reset role;
end $$;
rollback;
select 'OK: ultimo veiculo, datas, edicao, exclusao, inativos, sessao e permissoes; rollback completo' as resultado;
