-- Cadastros do pedido original. Não substitui modelos corrigidos posteriormente.

begin;

insert into public.veiculos (placa, modelo, tipo) values
('BBE9E35', 'PENDENTE - ALTERAR 1', 'veiculo'),
('BBE9E90', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('BBH1E97', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('BBH1E99', 'M.BENZ/ACCELO 815', 'veiculo'),
('BDU9C81', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('BDX3B59', 'Ford K 1.0 SE/SE PLUS Tivct flex 5P', 'veiculo'),
('BDY9I58', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('BEA5H11', 'VW/9. 170 DRC 4X2', 'veiculo'),
('BEY3F01', 'VW/9. 170 DRC 4X2', 'veiculo'),
('CZA1C09', 'GMC/16.220', 'veiculo'),
('ELW7J98', 'FIAT/STRADA FREEDOM CC', 'veiculo'),
('FHB8H95', 'VW/8. 160 DRC 4X2', 'veiculo'),
('FJT9I54', 'PENDENTE - ALTERAR 2', 'veiculo'),
('FOW2B35', 'PENDENTE - ALTERAR 3', 'veiculo'),
('GBQ9366', 'VW/8. 160 DRC 4X2', 'veiculo'),
('GEI8C98', 'VW/NOVA SAVEIRO RB MBVS', 'veiculo'),
('GIG9B72', 'PENDENTE - ALTERAR 4', 'veiculo'),
('JAJ1C55', 'VW/9. 170 DRC 4X2', 'veiculo'),
('KNC1076', 'PENDENTE - ALTERAR 5', 'veiculo'),
('KNH7B51', 'PENDENTE - ALTERAR 6', 'veiculo'),
('KQS8B71', 'M. BENZ/ATEGO 2430', 'veiculo'),
('KRK8F40', 'PENDENTE - ALTERAR 7', 'veiculo'),
('KRL8G19', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('KRN6A41', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('KRN6J98', 'PENDENTE - ALTERAR 8', 'veiculo'),
('KTV1201', 'PENDENTE - ALTERAR 9', 'veiculo'),
('KWM9F69', 'VW/17.190 WORKER', 'veiculo'),
('KXA6H28', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('KXC7C13', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('KXL9F47', 'VW/8. 160 DRC 4X2', 'veiculo'),
('KXU6H41', 'VW/8. 160 DRC 4X2', 'veiculo'),
('KYH5D78', 'PENDENTE - ALTERAR 10', 'veiculo'),
('KYX8A58', 'VW/17 . 190 CRM 4X2 EP', 'veiculo'),
('KZF4D30', 'FIAT/STRADA ADVENTURE CD', 'veiculo'),
('LMH3C97', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('LMH3G88', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('LMO7B21', 'VW/9. 170 DRC 4X2', 'veiculo'),
('LMP9H12', 'FORD', 'veiculo'),
('LMP9H23', 'FORD', 'veiculo'),
('LQK3B38', 'M.BENZ/1718', 'veiculo'),
('LQN6C18', 'RENAULT/SANDERO EXP1016V', 'veiculo'),
('LRB4716', 'I/KIA UK2500 HD SC', 'veiculo'),
('LRJ7G35', 'FORD', 'veiculo'),
('LRJ7G95', 'FORD', 'veiculo'),
('LRJ9B37', 'FORD', 'veiculo'),
('LSG7222', 'M.BENZ/ATEGO 1719', 'veiculo'),
('LSG7C27', 'M.BENZ/ATEGO 1719', 'veiculo'),
('LSJ9C70', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('LSK7B48', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('LSK7J36', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('LSK8E20', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('LSM9J59', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('LSN8D43', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('LSP7F42', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('LSV7340', 'HYUNDAI/HR HDB', 'veiculo'),
('LTD6433', 'HYUNDAI/HR HDB', 'veiculo'),
('LTQ7F95', 'VW 15.190', 'veiculo'),
('LTV8D48', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('LTX9J56', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('LUE3B62', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('LUH8E33', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('LUL8A32', 'PENDENTE - ALTERAR 11', 'veiculo'),
('LUL9I66', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('LUM3D11', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('LUO1G86', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('LUT7G94', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('QUJ3E09', 'SAVEIRO', 'veiculo'),
('RFY4C30', 'PENDENTE - ALTERAR 12', 'veiculo'),
('RIX1J87', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('RJA0I50', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('RJF4J47', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('RJG0F36', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('RJO0I33', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('RJP3C12', 'VW/9. 170 DRC 4X2', 'veiculo'),
('RJW0J69', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('RKB0A29', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('RKE3H26', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('RKI3I58', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('RKK0A22', 'M.BENZ/ACCELO 815 CE', 'veiculo'),
('SP-6539', 'RETROESCAVADEIRA', 'equipamento'),
('SP-7188', 'MINI RETROESCAVADEIRA', 'equipamento'),
('SSD8A74', 'VW/26.260 CRM 6X2', 'veiculo')
on conflict (placa) do nothing;

insert into public.funcionarios (nome, is_status, ativo) values
('Parado na Base', true, false),
('Ademilson Cezar de Mendonça', false, true),
('Ademir Jorge Barbosa da Silva', false, true),
('Adriano Firmino da Silva', false, true),
('Adriana da Silva Santos', false, true),
('Afonso Alves de Almeida', false, true),
('Alberto da Silva Rodrigues', false, true),
('Anderson da Conceição Fonseca', false, true),
('Anderson Donato Costa', false, true),
('André Luiz da Silva Pereira', false, true),
('Antonio Vanderleiz da Paz', false, true),
('Auricélio Andrade Oliveira', false, true),
('Carlos de Oliveira Barreto', false, true),
('Carlos Eduardo Alves Germano', false, true),
('Carlos Renato Dantas do Nascimento', false, true),
('Carlos Vinicius Polito Rodrigues', false, true),
('Claudio Cordeiro de Sousa', false, true),
('Clebisom de Azevedo Vieira', false, true),
('Daniel Gomes da Silva', false, true),
('Davi Bezerra Félix', false, true),
('David Decroix Viana', false, true),
('Davi Venancio Rodrigues', false, true),
('Djavan Henrique Vieira Grilo', false, true),
('Edilberto Sá Vianna da Silva Junior', false, true),
('Edreque Feliciano da Silva Santos', false, true),
('Edy Carlos Abreu Barreto', false, true),
('Erick Moraes Muniz', false, true),
('Eumir Silva da Gama Junior', false, true),
('Fabiano Suguiyama Vieira', false, true),
('Fabio Lima de Amorim', false, true),
('Fernando Junior Abreu do Nascimento', false, true),
('Fernando Pereira dos Prazeres', false, true),
('Fernando Ribeiro da Silva', false, true),
('Gabriel Álvaro Moreira', false, true),
('Gabriel Henrique da Silva Neves', false, true),
('Gilberto Bastos', false, true),
('Gilmar Miguel Rodrigues Soares', false, true),
('Gustavo Martins Gomes da Silva', false, true),
('Israel Rodrigues de Oliveira', false, true),
('Jean de Souza Silva', false, true),
('Jhoenis Lima Nunes', false, true),
('Jocimar de Araújo Eufrásio', false, true),
('Jocimar Lino Castro Areas', false, true),
('Joel Guilherme de Souza Junior', false, true),
('Johnatan Luiz Gomes de França', false, true),
('Jonhcklem Barreto da Cruz', false, true),
('José Baia da Silva', false, true),
('José Edvanio da Silva', false, true),
('Julio Cesar Duarte Pereira', false, true),
('Juraci Martins de Araújo', false, true),
('Leandro Franciscus Azeredo Alves da Silva', false, true),
('Leandro Teixeira Santos', false, true),
('Lucas Cordeiro Pereira', false, true),
('Lucas Melgaço da Silva', false, true),
('Lucas Severiano de Oliveira Caldas', false, true),
('Luis Henrique Nascimento dos Santos', false, true),
('Luis Jose Pereira', false, true),
('Luiz Felipe Costa Soares Rocha', false, true),
('Luiz Fernando de Souza Rabello', false, true),
('Luiz Ricardo Mazzucchelli Ferreira', false, true),
('Marcio Flores dos Santos', false, true),
('Marcos Alexandre Souza da Silva', false, true),
('Marcos Antonio Cordeiro Felismino', false, true),
('Marcos Antonio Garcez Serqueira', false, true),
('Mauro Cesar Alves Ferreira de Souza', false, true),
('Max Sandro da Costa Figueredo', false, true),
('Maximiliano da Silva Pereira', false, true),
('Paulo Ricardo Tito', false, true),
('Pedro Paulo Mendes Baldez', false, true),
('Ramon Lopes do Livramento da Silva', false, true),
('Reinaldo da Silva Barros Junior', false, true),
('Roberto David Silva', false, true),
('Rodrigo Melo', false, true),
('Robson Luiz Ribeiro Pimentel', false, true),
('Robson Pargas Novaes', false, true),
('Rodrigo dos Santos Dias', false, true),
('Rodrigo Eduardo Carvalho de Oliveira', false, true),
('Rogerio Rangel Rosa', false, true),
('Severino Alves Barreto', false, true),
('Sérgio Reis de Jesus Bittencourt', false, true),
('Sidnei Carvalho da Silva', false, true),
('Silvanio Madureira Campos', false, true),
('Thiago Alexandre Frutuoso de Lima', false, true),
('Thiago Barcello Alves', false, true),
('Thomaz da Silva', false, true),
('Túlio da Silva Mariano', false, true),
('Uilliam Simões Fernandes', false, true),
('Vagner Soares Marinho', false, true),
('Valter Pereira da Silva', false, true),
('Valdinei Machado De Laia', false, true),
('Vitor Cesar Silva Domingos Oliveira', false, true),
('Wagner Souza de Oliveira', false, true),
('Wagner José da Silva', false, true),
('Wellington Tavares', false, true),
('Wallace Felizardo de Queiroz', false, true),
('Walter Cardoso Gonzaga', false, true),
('Wanderson Sabino Cabral', false, true),
('William de Souza Campos Chagas', false, true),
('Willis Martins Ferreira', false, true),
('Willye Cristiano Pessanha Ramos', false, true),
('Wilson da Silva Ramos', false, true),
('Wilson Vieira Mendes', false, true),
('Wislley Costa Santos', false, true)
on conflict (nome) do nothing;

insert into public.contratos (nome) values
('Belford Roxo'),
('Buri'),
('Campos dos Goytacazes'),
('Duque de Caxias'),
('Magé'),
('Natal'),
('Paty do Alferes'),
('São Gonçalo'),
('Saquarema')
on conflict (nome) do nothing;

insert into public.tipos_manutencao (nome) values
('Preventiva'),
('Corretiva'),
('Revisão'),
('Pneus'),
('Elétrica'),
('Mecânica'),
('Funilaria'),
('Outros')
on conflict (nome) do nothing;

commit;
